### ISSUE TITLE
Set User default schema

### ISSUE THREAD

**Issue by odinuv** [keboola/db-writer-snowflake#18]
https://keboola.slack.com/conversation/zendesk/p1494592387853994

Set default schema or at least let the user know in the UI that he must set default schema

**Comment by ujovlado** [comment]
Similar problem here:
https://keboola.zendesk.com/agent/tickets/8207

**Comment by pivnicek** [comment]
Also here:
https://keboola.zendesk.com/agent/tickets/9080

**Comment by ErikZigo** [comment]
Uz jsem nasel problem.

Schema je od sameho zacatku jako povinny parametr v spojeni a predava se v DNS stringu. Takze vse by melo fungovat jak ma a zadny `DEFAULT_NAMESPACE` neni potreba.

Problem nastane pokud jako `schema` zadam neexistujici schema. Pak se ODBC normalne pripoji, ale nezarve zadnou chybu.

Query nad tabulkou pak konci chybou `Cannot perform DROP. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.`
