### ISSUE TITLE
Error Writeru do cizího snowflake blbě loguje 

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-snowflake#27]
Fisa [hlásí](https://keboola.zendesk.com/agent/tickets/7843) error z loadu do Snowflake, kterej není náš. Jde o tenhle job: https://connection.keboola.com/admin/projects/4191/jobs/349454445?q=

![image](https://user-images.githubusercontent.com/1427901/35405118-781453ca-0205-11e8-80b3-8a5009e5ff53.png)

Mělo by to imho logovat líp.

**Comment by pivnicek** [comment]
duplicate: https://github.com/keboola/db-extractor-snowflake/issues/37
