### ISSUE TITLE
Restrict permissions to or remove default/sample schemas

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-writer-snowflake#28]
The writer user sees some default schemas that may confuse them
![image](https://user-images.githubusercontent.com/569139/35441147-a4dea6ec-02a2-11e8-8685-7f9b12e36da6.png)
We should probably either remove or restrict these schemas.

**Comment by Halama** [comment]
přesnul jsem to sem https://github.com/keboola/connection/issues/1194
