### ISSUE TITLE
Druhý Writer v projektu

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-snowflake#3]
Pokud založím druhý writer v projektu, dostane stejné credentials. Vidět je to tady:

**první writer**
([https://connection.keboola.com/admin/projects/1507/writers/keboola.wr-db-snowflake/217319889/credentials](https://connection.keboola.com/admin/projects/1507/writers/keboola.wr-db-snowflake/217319889/credentials))

vs **druhý writer** 
([https://connection.keboola.com/admin/projects/1507/writers/keboola.wr-db-snowflake/217324571/credentials](https://connection.keboola.com/admin/projects/1507/writers/keboola.wr-db-snowflake/217324571/credentials))

Jak tak nad tím přemýšlím (primárně kvůli provozním nákladům), asi by nebylo od věci omezovat počet Snowflake Writerů, co jsou dodaný náma.

**Comment by MiroCillik** [comment]
Je to problem UI, davam na @kacurez

**Comment by kacurez** [comment]
fixed in https://github.com/keboola/kbc-ui/commit/9173def2fb87431dcfa816a762e0b722b5dc83f5
