### ISSUE TITLE
Nefunkční heslo do Snowflake DB

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-snowflake#31]
Přišli jsme na heslo, pod kterém se dá přihlásit do Snowflake přes jejich web klienta, ale writer failne.

Nepoužitelné heslo je:

```
bEdJ4wwkt2b7ute.MwHPc4#Le39q;DQ77*pb?Xkw7mBMr},vpF8^XJEwYC]ENM,Q
```

Tady je vidět že ho UI při "TEST CREDENTIALS" posílá správně: https://monosnap.com/file/HOxnPk8JdrKH5EQc2xStQyc16QE5jK

Zkusili jsme odjebat divné znaky a zachovat délku:

```
bEdJ4wwkt2b7ute_MwHPc4_Le39q_DQ77_pb_Xkw7mBMr__vpF8_XJEwYC_ENM_Q
```

a to prošlo.

Heslo dál není nikde použité.

**Comment by padak** [comment]
Konfigurace v produkci: https://connection.eu-central-1.keboola.com/admin/projects/133/writers/keboola.wr-db-snowflake/7316315/credentials

Error ID: `docker-fe48d3f348aae1be3c130080745313ee`

**Comment by ErikZigo** [comment]
Je to strednikem v heslu ";". Zatim nevim jak to obejit a jestli to je bug v php, nebo Snowflake writeru.

**Comment by ErikZigo** [comment]
Podle dokumentace ODBC musi byt hodnota property obsahujici `;` obalena do slozenych zavorek.


Tohle by melo zabrat, resi to situci kdy by byla v heslu i prava slozena zavorka. Ta musi byt zdvojena.
```
odbc_connect(
    $dsn,
    $user,
    '{' . str_replace('}', '}}', $password . '}'
)
```

**Comment by natocTo** [comment]
Zaleženo v Jire https://keboola.atlassian.net/browse/COM-1220
