### ISSUE TITLE
Remove ROOT_PATH constant

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-writer-snowflake#35]

**Comment by ErikZigo** [comment]
i v kbc to tak je, vcetne ignore v phpstan.neon

**Comment by Halama** [comment]
v kbc to tak je jenom proto že by to znamenalo větší množství změn v tom PR kde jsem zaváděl phpstan tak jsem to tam radši nechal.
Jinak ve všech appkách jsem tyhle konstanty vyhazoval když jsem něco updatoval, většinou tam k ničemu nebyly.
