### ISSUE TITLE
Progress notifikace při vyrábění DB

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-snowflake#5]
V UI není vidět, jestli se něco děje, když to setupuje náš snowflake:
![image](https://cloud.githubusercontent.com/assets/1427901/21096426/27d6a31e-c060-11e6-8d8a-d8e2401e7694.png)
^^ tady by se hodilo nějaký "točící kolečko"

P.

**Comment by ErikZigo** [comment]
Koukal jsem na aktualni stav a tam uz kolecko je, tak to tady zaviram.

![image](https://user-images.githubusercontent.com/1726727/45269861-483ec480-b495-11e8-8aa7-5e1f56d09a6a.png)
